### ISSUE TITLE
后台密码

### ISSUE THREAD

**Issue by xmx0625** [LiuYuYang01/Thrive_Api_Py#2]
后台管理的账号和密码  账号是liuyuyang 但是密码呢

**Comment by xmx0625** [comment]
> 后台管理的账号和密码 账号是liuyuyang 但是密码呢

**Comment by LiuYuYang01** [comment]
123123

**Comment by xmx0625** [comment]
谢谢




心若无痕
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiuYuYang01/Thrive_Api_Py"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月19日(星期一) 晚上8:12
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [LiuYuYang01/Thrive_Api_Py] 后台密码 (Issue #2)





 
123123
